version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms64m -Xmx128m"
      - "ES_HEAP_SIZE=100m"
      - "MAX_LOCKED_MEMORY=100000"
      - "MAX_OPEN_FILES=65535"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/data/elasticsearch.yml
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
      rollback_config:
        order: start-first

  db:
    image: mariadb:10.5.4
    environment:
      - MYSQL_ROOT_PASSWORD=example
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      rollback_config:
        order: start-first

  ftown:
    image: ftown:v1.0
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
