version: "3.8"
services:
  ftown:
    image: ftown:v1.5
    container_name: ftown
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - socket-dir:/socket
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  proxy:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    labels:
      - sh.acme.autoload.domain=fythonfang.com
    volumes:
      - ./Ops/nginx/conf.d:/etc/nginx/conf.d
      - ./Ops/nginx/ssl:/etc/nginx/ssl
      - ./app:/srv/app
      - socket-dir:/socket

  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    command: daemon
    volumes:
      - ./Ops/acme-out:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=fythonfang.com
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/fythonfang.com/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/fythonfang.com/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/fythonfang.com/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/fythonfang.com/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ELASTIC_PASSWORD=123456"
      - "ES_JAVA_OPTS=-Xms64m -Xmx128m"
      - "ES_HEAP_SIZE=100m"
      - "MAX_LOCKED_MEMORY=100000"
      - "MAX_OPEN_FILES=65535"
    volumes:
      - ./Ops/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/data/elasticsearch.yml
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
      rollback_config:
        order: start-first

  db:
    image: mariadb:10.5.4
    container_name: mariadb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
    volumes:
      - ./Ops/mysql:/var/lib/mysql

volumes:
  socket-dir:
