"""empty message

Revision ID: 007e528522ec
Revises: 579abb3aa450
Create Date: 2017-02-20 19:46:53.466334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007e528522ec'
down_revision = '579abb3aa450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
