"""empty message

Revision ID: 0f1198ef303f
Revises: 007e528522ec
Create Date: 2017-03-13 21:11:09.644887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1198ef303f'
down_revision = '007e528522ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###
