"""empty message

Revision ID: 171fd94e014a
Revises: 0f1198ef303f
Create Date: 2017-03-22 10:49:19.962798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171fd94e014a'
down_revision = '0f1198ef303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
