"""empty message

Revision ID: 67974e7d3002
Revises: e0617918d6d3
Create Date: 2017-09-21 11:50:53.302708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67974e7d3002'
down_revision = 'e0617918d6d3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_collection():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=256), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('star', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_collection():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends')
    # ### end Alembic commands ###

