"""empty message

Revision ID: 690be2642000
Revises: 67974e7d3002
Create Date: 2017-09-26 16:50:03.150962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690be2642000'
down_revision = '67974e7d3002'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_collection():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('specs', sa.Text(), nullable=True),
    sa.Column('collect', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_collection():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment')
    # ### end Alembic commands ###

