"""empty message

Revision ID: 7d8b74a08741
Revises: 2ccc46694fd0
Create Date: 2017-05-19 10:02:47.272964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8b74a08741'
down_revision = '2ccc46694fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
