"""empty message

Revision ID: a9417ff0b42b
Revises: 7d8b74a08741
Create Date: 2017-08-23 14:34:17.870143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9417ff0b42b'
down_revision = '7d8b74a08741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anonymous', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('incog_email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'incog_email')
    op.drop_column('users', 'anonymous')
    # ### end Alembic commands ###
