"""empty message

Revision ID: b8aa40064346
Revises: a9417ff0b42b
Create Date: 2017-08-28 15:11:06.020588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8aa40064346'
down_revision = 'a9417ff0b42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('brief_title', sa.String(length=240), nullable=True))
    op.create_index(op.f('ix_posts_brief_title'), 'posts', ['brief_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_brief_title'), table_name='posts')
    op.drop_column('posts', 'brief_title')
    # ### end Alembic commands ###
